import { GymConfig } from '@/types';

export const DEFAULT_AGENCY = {
  agencyName: 'FitDigital Agency',
  calBookingUrl: 'https://calendly.com/fitdigital-demos/strategy-session',
  repName: 'Taiwo Adediji',
  repTitle: 'Head of Fitness Partnerships',
  repEmail: 'taiwo.adediji.apps@gmail.com',
  repPhone: '+1 (512) 843-9120',
};

export const PRESET_DEMOS: Record<string, GymConfig> = {
  'apex-fitness': {
    id: 'demo-apex',
    slug: 'apex-fitness',
    name: 'Apex Athletic Club',
    tagline: 'Austin’s Premier Performance & Wellness Sanctuary',
    location: 'Austin, TX (Downtown)',
    primaryColor: '#10B981', // Emerald / Neon Lime
    secondaryColor: '#059669',
    isDarkMode: true,
    logoMonogram: 'APEX',
    industryType: 'Athletic Club',
    customPushMessage: '🔥 Apex Reminder: 2 spots left for 6:00 PM HIIT Burn tonight! Tap to reserve.',
    agencySettings: DEFAULT_AGENCY,
    features: {
      classBooking: true,
      trainerScheduler: true,
      loyaltyPunchCard: true,
      pushNotification: true,
      passPurchase: true,
    },
    homeConfig: {
      greeting: 'Welcome back, Alex!',
      memberBadge: 'VIP Member',
      membershipCardTitle: 'All-Access Performance Pass',
      quickAction1Label: 'Book Class',
      quickAction2Label: 'Scan Pass',
      quickAction3Label: 'Streak',
      featuredClassBadge: 'Up Next Today',
    },
    scheduleConfig: {
      title: 'Live Class Schedule',
      subtitle: 'Book your workout slot in real time',
      categories: ['All', 'HIIT', 'Strength', 'Yoga', 'Spin'],
      confirmationToast: "You're booked! Added to Apple Calendar ✓",
    },
    trainersConfig: {
      title: 'Coaches & Trainers',
      subtitle: '1-on-1 private coaching & performance assessments',
    },
    rewardsConfig: {
      title: 'Member Rewards',
      subtitle: 'Punch card, streaks & member perks',
      tierBadge: 'Tier 2 Athlete',
      monthlyGoal: 20,
      startingStreak: 14,
    },
    trainers: [
      {
        id: 't-1',
        name: 'Jordan Stone',
        title: 'Lead Strength Coach & Ex-D1 Trainer',
        specialties: ['Hypertrophy', 'Olympic Lifting', 'Body Recomp'],
        avatar: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&auto=format&fit=crop&q=80',
        bio: 'CSCS certified with 9+ years developing custom strength programs for executive athletes and competitors.',
        rate: 85,
        rating: 4.98,
        sessionsCompleted: 420,
      },
      {
        id: 't-2',
        name: 'Elena Rostova',
        title: 'Master Mobility & Athletic Conditioning',
        specialties: ['Athletic Flow', 'Functional Core', 'Postural Rehab'],
        avatar: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&auto=format&fit=crop&q=80',
        bio: 'Specializing in longevity, explosive rotational power, and injury prevention for athletes.',
        rate: 80,
        rating: 4.95,
        sessionsCompleted: 310,
      },
      {
        id: 't-3',
        name: 'Marcus Hayes',
        title: 'HIIT & Endurance Director',
        specialties: ['VO2 Max', 'Kettlebell Flow', 'Metabolic Burn'],
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        bio: 'High-energy trainer focused on cardiovascular endurance and metabolic transformation.',
        rate: 75,
        rating: 4.92,
        sessionsCompleted: 275,
      },
    ],
    classes: [
      {
        id: 'c-1',
        name: 'HIIT Burn & Shred',
        time: '6:00 PM',
        duration: '50m',
        instructor: 'Marcus Hayes',
        room: 'Studio Alpha',
        category: 'HIIT',
        spotsLeft: 2,
        totalSpots: 18,
        day: 'Mon',
        intensity: 'Extreme',
      },
      {
        id: 'c-2',
        name: 'Olympic Barbell Club',
        time: '7:15 AM',
        duration: '60m',
        instructor: 'Jordan Stone',
        room: 'Iron Pit',
        category: 'Strength',
        spotsLeft: 5,
        totalSpots: 12,
        day: 'Mon',
        intensity: 'High',
      },
      {
        id: 'c-3',
        name: 'Athletic Recovery & Flow',
        time: '12:00 PM',
        duration: '45m',
        instructor: 'Elena Rostova',
        room: 'Zen Loft',
        category: 'Yoga',
        spotsLeft: 8,
        totalSpots: 20,
        day: 'Tue',
        intensity: 'Medium',
      },
      {
        id: 'c-4',
        name: 'Turbine Spin & Beats',
        time: '5:30 PM',
        duration: '45m',
        instructor: 'Sasha Fox',
        room: 'Cycle Vault',
        category: 'Spin',
        spotsLeft: 3,
        totalSpots: 24,
        day: 'Wed',
        intensity: 'High',
      },
    ],
    rewards: [
      {
        id: 'r-1',
        title: 'Free Artisan Protein Shake',
        reqWorkouts: 5,
        description: 'Claim any gourmet shake or smoothie at the Apex Refuel Bar.',
        unlocked: true,
        code: 'APEX-SHAKE-90',
        icon: 'shake',
      },
      {
        id: 'r-2',
        title: '20% Off Apex Pro Apparel',
        reqWorkouts: 10,
        description: 'Valid for hoodies, tees, training shorts, or gym bags in the pro shop.',
        unlocked: true,
        code: 'APEX-GEAR-20',
        icon: 'discount',
      },
      {
        id: 'r-3',
        title: 'Complimentary 1-on-1 PT Session',
        reqWorkouts: 15,
        description: '60-minute private performance assessment with any Master Coach.',
        unlocked: false,
        code: 'APEX-COACH-FREE',
        icon: 'pt',
      },
      {
        id: 'r-4',
        title: 'Apex VIP Hall of Fame Plaque',
        reqWorkouts: 20,
        description: 'Custom laser-engraved metal shaker bottle and VIP lounge access.',
        unlocked: false,
        code: 'APEX-ELITE-LIFETIME',
        icon: 'trophy',
      },
    ],
  },

  'ironforge-crossfit': {
    id: 'demo-crossfit',
    slug: 'ironforge-crossfit',
    name: 'IronForge CrossFit Box',
    tagline: 'Forging Unbreakable Functional Fitness & Grit',
    location: 'Denver, CO (Rino District)',
    primaryColor: '#F97316', // Electric Orange / Amber
    secondaryColor: '#EA580C',
    isDarkMode: true,
    logoMonogram: 'FORGE',
    industryType: 'CrossFit Box',
    customPushMessage: '⚡ IronForge WOD Released: "The Anvil" at 6:30 PM. 3 spots left on the whiteboard!',
    agencySettings: DEFAULT_AGENCY,
    features: {
      classBooking: true,
      trainerScheduler: true,
      loyaltyPunchCard: true,
      pushNotification: true,
      passPurchase: true,
    },
    homeConfig: {
      greeting: 'Welcome back, Athlete Dave!',
      memberBadge: 'Founding Athlete',
      membershipCardTitle: 'Unlimited Box Access Pass',
      quickAction1Label: 'Daily WOD',
      quickAction2Label: 'Scan In',
      quickAction3Label: 'PR Streak',
      featuredClassBadge: 'Today’s Whiteboard WOD',
    },
    scheduleConfig: {
      title: 'Box WOD & Rig Schedule',
      subtitle: 'Reserve your rig barbell and platform',
      categories: ['All', 'CrossFit', 'Strength', 'Gymnastics', 'Team'],
      confirmationToast: "Whiteboard spot secured! See you on the floor ✓",
    },
    trainersConfig: {
      title: 'CrossFit Level 3 Coaches',
      subtitle: 'Barbell mechanics, gymnastics & competition prep',
    },
    rewardsConfig: {
      title: 'Iron Athlete Passport',
      subtitle: 'Monthly attendance stamps & box gear',
      tierBadge: 'Iron Rig Master',
      monthlyGoal: 24,
      startingStreak: 18,
    },
    trainers: [
      {
        id: 't-cf-1',
        name: 'Coach Dave Miller',
        title: 'CrossFit Level 3 Coach & Box Owner',
        specialties: ['WOD Strategy', 'Gymnastic Ring Work', 'Barbell Cycling'],
        avatar: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&auto=format&fit=crop&q=80',
        bio: '12-year box veteran and former regional competitor. Passionate about scaled progressions for every athlete.',
        rate: 90,
        rating: 4.99,
        sessionsCompleted: 580,
      },
      {
        id: 't-cf-2',
        name: 'Brooke Hansen',
        title: 'USAW Weightlifting Specialist',
        specialties: ['Snatch Tech', 'Clean & Jerk', 'Kettlebell Snatch'],
        avatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&auto=format&fit=crop&q=80',
        bio: 'Former collegiate lifter teaching biomechanics, speed under the bar, and hip explosion.',
        rate: 85,
        rating: 4.96,
        sessionsCompleted: 340,
      },
    ],
    classes: [
      {
        id: 'c-cf-1',
        name: 'Daily WOD: "The Anvil"',
        time: '6:00 AM',
        duration: '60m',
        instructor: 'Coach Dave Miller',
        room: 'Rig 1 (Main Box)',
        category: 'CrossFit',
        spotsLeft: 3,
        totalSpots: 16,
        day: 'Mon',
        intensity: 'Extreme',
      },
      {
        id: 'c-cf-2',
        name: 'Barbell Club: Snatch Waves',
        time: '5:30 PM',
        duration: '60m',
        instructor: 'Brooke Hansen',
        room: 'Oly Platform Area',
        category: 'Strength',
        spotsLeft: 4,
        totalSpots: 10,
        day: 'Mon',
        intensity: 'High',
      },
    ],
    rewards: [
      {
        id: 'r-cf-1',
        title: 'IronForge Custom Wrist Wraps',
        reqWorkouts: 6,
        description: 'Heavy-duty cotton wrist supports embroidered with your member ID.',
        unlocked: true,
        code: 'FORGE-WRAPS-FREE',
        icon: 'discount',
      },
      {
        id: 'r-cf-2',
        title: 'Electrolyte Tub or Shaker Box',
        reqWorkouts: 12,
        description: 'Full tub of high-grade clean hydration fuel at check-in.',
        unlocked: true,
        code: 'FORGE-HYDRO-01',
        icon: 'shake',
      },
    ],
  },

  'zenith-pilates': {
    id: 'demo-pilates',
    slug: 'zenith-pilates',
    name: 'Zenith Pilates & Sanctuary',
    tagline: 'Mindful Reformer & Breathwork Studio',
    location: 'Santa Monica, CA (Ocean Ave)',
    primaryColor: '#06B6D4', // Cyan / Teal
    secondaryColor: '#0891B2',
    isDarkMode: false, // Light aesthetic
    logoMonogram: 'ZENITH',
    industryType: 'Pilates & Yoga',
    customPushMessage: '🌿 Candlelight Reformer tonight at 7:00 PM has 1 spot left! Tap to reserve your carriage.',
    agencySettings: DEFAULT_AGENCY,
    features: {
      classBooking: true,
      trainerScheduler: true,
      loyaltyPunchCard: true,
      pushNotification: true,
      passPurchase: true,
    },
    homeConfig: {
      greeting: 'Welcome back, Chloe!',
      memberBadge: 'Carriage Club Member',
      membershipCardTitle: 'Sanctuary Reformer Pass',
      quickAction1Label: 'Book Carriage',
      quickAction2Label: 'Studio Pass',
      quickAction3Label: 'Flow Streak',
      featuredClassBadge: 'Today’s Restorative Flow',
    },
    scheduleConfig: {
      title: 'Carriage & Mat Flows',
      subtitle: 'Allegro 2 Reformers, Sound Baths & Infrared Yin',
      categories: ['All', 'Pilates', 'Yoga', 'Breathwork', 'Restorative'],
      confirmationToast: "Your reformer carriage is reserved! Namaste ✓",
    },
    trainersConfig: {
      title: 'Master Instructors & Gurus',
      subtitle: 'Reformer biomechanics, sound healing & alignment',
    },
    rewardsConfig: {
      title: 'Zenith Flow Loyalty',
      subtitle: 'Mindful class check-ins & organic studio perks',
      tierBadge: 'Lotus Sanctuary Member',
      monthlyGoal: 16,
      startingStreak: 10,
    },
    trainers: [
      {
        id: 't-zp-1',
        name: 'Chloe Laurent',
        title: 'Reformer & Classical Pilates Master',
        specialties: ['Allegro 2 Reformer', 'Deep Core Sculpt', 'Prenatal Alignment'],
        avatar: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&auto=format&fit=crop&q=80',
        bio: 'Trained in Paris and Los Angeles, Chloe guides low-impact high-burn reformer flows that lengthen and tone.',
        rate: 95,
        rating: 5.0,
        sessionsCompleted: 490,
      },
      {
        id: 't-zp-2',
        name: 'Maya Vance',
        title: 'Sound Bath & Yin Yoga Lead',
        specialties: ['Chakra Alignment', 'Pranayama', 'Sound Bowls'],
        avatar: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&auto=format&fit=crop&q=80',
        bio: 'Guiding soothing restorative sessions with crystal singing bowls and therapeutic breathwork.',
        rate: 85,
        rating: 4.97,
        sessionsCompleted: 260,
      },
    ],
    classes: [
      {
        id: 'c-zp-1',
        name: 'Reformer Sculpt & Length',
        time: '8:30 AM',
        duration: '50m',
        instructor: 'Chloe Laurent',
        room: 'Carriage Studio 1',
        category: 'Pilates',
        spotsLeft: 2,
        totalSpots: 10,
        day: 'Mon',
        intensity: 'Medium',
      },
      {
        id: 'c-zp-2',
        name: 'Infrared Candlelight Yin',
        time: '7:00 PM',
        duration: '60m',
        instructor: 'Maya Vance',
        room: 'Sanctuary Lounge',
        category: 'Yoga',
        spotsLeft: 1,
        totalSpots: 14,
        day: 'Mon',
        intensity: 'All Levels',
      },
    ],
    rewards: [
      {
        id: 'r-zp-1',
        title: 'Zenith Organic Grip Socks',
        reqWorkouts: 4,
        description: 'Custom silicone grip studio socks complimentary at reception.',
        unlocked: true,
        code: 'ZEN-SOCKS-01',
        icon: 'towel',
      },
      {
        id: 'r-zp-2',
        title: 'Cold-Pressed Green Glow Juice',
        reqWorkouts: 8,
        description: 'Fresh organic pressed juice after your reformer session.',
        unlocked: true,
        code: 'ZEN-JUICE-FREE',
        icon: 'shake',
      },
    ],
  },

  'rumble-boxing': {
    id: 'demo-boxing',
    slug: 'rumble-boxing',
    name: 'Rumble Boxing & HIIT Lab',
    tagline: '10 Rounds of Dark Room Boxing & Strength',
    location: 'Miami, FL (Brickell)',
    primaryColor: '#EC4899', // Electric Pink / Neon Crimson
    secondaryColor: '#DB2777',
    isDarkMode: true,
    logoMonogram: 'RUMBLE',
    industryType: 'Boxing & HIIT',
    customPushMessage: '🥊 Tonight’s 6:45 PM Heavy Bag Knockout has 2 bags open! Grab your gloves.',
    agencySettings: DEFAULT_AGENCY,
    features: {
      classBooking: true,
      trainerScheduler: true,
      loyaltyPunchCard: true,
      pushNotification: true,
      passPurchase: true,
    },
    homeConfig: {
      greeting: 'Welcome to the Ring, Tyson!',
      memberBadge: 'Championship Fighter',
      membershipCardTitle: 'Unlimited Bag & Bell Pass',
      quickAction1Label: 'Book Bag',
      quickAction2Label: 'Locker Pass',
      quickAction3Label: 'Rounds Streak',
      featuredClassBadge: 'Tonight’s Main Event',
    },
    scheduleConfig: {
      title: '10-Round Fight Schedule',
      subtitle: 'Aqua bags, heavy bells, and dark room DJ beats',
      categories: ['All', 'Boxing', 'HIIT', 'Speed Lab', 'DJ Night'],
      confirmationToast: "Your heavy bag is locked in! Gloves up ✓",
    },
    trainersConfig: {
      title: 'Fight Coaches & Pad Masters',
      subtitle: 'Pro mitt work, knockout combinations & defense',
    },
    rewardsConfig: {
      title: 'Knockout Club Passport',
      subtitle: '10 rounds logged = championship hardware',
      tierBadge: 'Golden Gloves Tier',
      monthlyGoal: 20,
      startingStreak: 12,
    },
    trainers: [
      {
        id: 't-rb-1',
        name: 'Tyson "Blade" Ortiz',
        title: 'Head Boxing Coach & Golden Gloves Champ',
        specialties: ['Mitt Work', 'Footwork & Angles', 'Knockout Power'],
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
        bio: 'Former pro fighter bringing championship combos and boxing conditioning to everyday fighters.',
        rate: 100,
        rating: 4.99,
        sessionsCompleted: 610,
      },
      {
        id: 't-rb-2',
        name: 'Kira Sterling',
        title: 'HIIT Conditioning & Bag Specialist',
        specialties: ['Aqua Bag Combos', 'Dumbbell Intervals', 'Core Shred'],
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
        bio: 'High energy beats, sharp technique, and relentless motivation on the mic.',
        rate: 85,
        rating: 4.94,
        sessionsCompleted: 350,
      },
    ],
    classes: [
      {
        id: 'c-rb-1',
        name: '10 Rounds: Bags & Bells',
        time: '6:45 PM',
        duration: '50m',
        instructor: 'Tyson "Blade" Ortiz',
        room: 'The Ring (Dark Room)',
        category: 'Boxing',
        spotsLeft: 2,
        totalSpots: 24,
        day: 'Mon',
        intensity: 'Extreme',
      },
    ],
    rewards: [
      {
        id: 'r-rb-1',
        title: 'Rumble Quick-Gel Handwraps',
        reqWorkouts: 5,
        description: 'Pro grade padded inner gloves with quick wrist wrap.',
        unlocked: true,
        code: 'RUMBLE-WRAPS-FREE',
        icon: 'towel',
      },
    ],
  },
};

export function ensureGymConfig(cfg: Partial<GymConfig> | null | undefined): GymConfig {
  const base = PRESET_DEMOS['apex-fitness'];
  if (!cfg) return base;

  const raw = cfg as Partial<GymConfig>;
  const agency = raw.agencySettings || base.agencySettings;

  return {
    ...base,
    ...raw,
    id: raw.id || `demo-${raw.slug || 'custom'}`,
    name: raw.name || base.name,
    slug: raw.slug || base.slug,
    tagline: raw.tagline || base.tagline,
    location: raw.location || base.location,
    primaryColor: raw.primaryColor || base.primaryColor,
    secondaryColor: raw.secondaryColor || base.secondaryColor,
    isDarkMode: raw.isDarkMode ?? base.isDarkMode,
    logoMonogram: raw.logoMonogram || (raw.name ? raw.name.slice(0, 2).toUpperCase() : base.logoMonogram),
    industryType: raw.industryType || base.industryType,
    customPushMessage: raw.customPushMessage || base.customPushMessage,
    agencySettings: {
      agencyName: agency?.agencyName || 'FitDigital Agency',
      calBookingUrl: '',
      repName: 'Taiwo Adediji',
      repTitle: agency?.repTitle || 'Head of Fitness Partnerships',
      repEmail: 'taiwo.adediji.apps@gmail.com',
      repPhone: agency?.repPhone || '+1 (512) 843-9120',
    },
    features: {
      classBooking: raw.features?.classBooking ?? true,
      trainerScheduler: raw.features?.trainerScheduler ?? true,
      loyaltyPunchCard: raw.features?.loyaltyPunchCard ?? true,
      pushNotification: raw.features?.pushNotification ?? true,
      passPurchase: raw.features?.passPurchase ?? true,
    },
    homeConfig: {
      greeting: raw.homeConfig?.greeting ?? base.homeConfig?.greeting ?? 'Welcome back, Alex!',
      memberBadge: raw.homeConfig?.memberBadge ?? base.homeConfig?.memberBadge ?? 'VIP Member',
      membershipCardTitle: raw.homeConfig?.membershipCardTitle ?? base.homeConfig?.membershipCardTitle ?? 'All-Access Performance Pass',
      quickAction1Label: raw.homeConfig?.quickAction1Label ?? base.homeConfig?.quickAction1Label ?? 'Book Class',
      quickAction2Label: raw.homeConfig?.quickAction2Label ?? base.homeConfig?.quickAction2Label ?? 'Scan Pass',
      quickAction3Label: raw.homeConfig?.quickAction3Label ?? base.homeConfig?.quickAction3Label ?? 'Streak',
      featuredClassBadge: raw.homeConfig?.featuredClassBadge ?? base.homeConfig?.featuredClassBadge ?? 'Up Next Today',
    },
    scheduleConfig: {
      title: raw.scheduleConfig?.title ?? base.scheduleConfig?.title ?? 'Live Class Schedule',
      subtitle: raw.scheduleConfig?.subtitle ?? base.scheduleConfig?.subtitle ?? 'Book your workout slot in real time',
      categories:
        raw.scheduleConfig?.categories && raw.scheduleConfig.categories.length > 0
          ? raw.scheduleConfig.categories
          : base.scheduleConfig?.categories ?? ['All', 'HIIT', 'Strength', 'Yoga', 'Spin'],
      confirmationToast:
        raw.scheduleConfig?.confirmationToast ?? base.scheduleConfig?.confirmationToast ?? "You're booked! Added to Apple Calendar ✓",
    },
    trainersConfig: {
      title: raw.trainersConfig?.title ?? base.trainersConfig?.title ?? 'Coaches & Trainers',
      subtitle: raw.trainersConfig?.subtitle ?? base.trainersConfig?.subtitle ?? '1-on-1 private coaching & performance assessments',
    },
    rewardsConfig: {
      title: raw.rewardsConfig?.title ?? base.rewardsConfig?.title ?? 'Member Rewards',
      subtitle: raw.rewardsConfig?.subtitle ?? base.rewardsConfig?.subtitle ?? 'Punch card, streaks & member perks',
      tierBadge: raw.rewardsConfig?.tierBadge ?? base.rewardsConfig?.tierBadge ?? 'Tier 2 Athlete',
      monthlyGoal: raw.rewardsConfig?.monthlyGoal ?? base.rewardsConfig?.monthlyGoal ?? 20,
      startingStreak: raw.rewardsConfig?.startingStreak ?? base.rewardsConfig?.startingStreak ?? 14,
    },
    classes: Array.isArray(raw.classes) && raw.classes.length > 0 ? raw.classes : (base.classes || []),
    trainers: Array.isArray(raw.trainers) && raw.trainers.length > 0 ? raw.trainers : (base.trainers || []),
    rewards: Array.isArray(raw.rewards) && raw.rewards.length > 0 ? raw.rewards : (base.rewards || []),
  };
}
